### ISSUE TITLE
Automate Deconseq runs via testsuite

### ISSUE THREAD

**Issue by brainstorm** [SciLifeLab/facs#58]
Use the structure present to generate a Deconseq test integrated with the general testsuite:

http://deconseq.sourceforge.net/

**Comment by RB7486** [comment]
Hi,
I am getting same error like above 
ERROR: Could not create tsv file /../../../deconseq-standalone-.4.3/1447251957_hsref_hs_ref_GRCh37_s1/hs_ref_GRCh37_s1.tsv: No such file or directory.
 Is it the issue related to path or permission or anything else?

**Comment by brainstorm** [comment]
This project was discontinued a while ago, sorry :/
